// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_path_packets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNodePathPublicKey = `-- name: GetNodePathPublicKey :one

SELECT public_key FROM nodes WHERE id = $1
`

// Copyright 2026 Beacon Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) GetNodePathPublicKey(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getNodePathPublicKey, id)
	var public_key []byte
	err := row.Scan(&public_key)
	return public_key, err
}

const listNodePathPackets = `-- name: ListNodePathPackets :many
WITH snapshot AS (
  SELECT COALESCE(NULLIF($1::bigint, 0),
                  (SELECT COALESCE(max(id), 0) FROM packet_observations))::bigint AS id
), matches AS MATERIALIZED (
  SELECT po.packet_hash, min(po.id)::bigint AS first_match_id,
         max(po.id)::bigint AS last_match_id, count(*)::bigint AS matching_observations
  FROM packet_observations po
  JOIN packets p ON p.packet_hash = po.packet_hash
  CROSS JOIN snapshot
  WHERE po.id <= snapshot.id
    AND (cardinality($2::text[]) = 0 OR po.iata = ANY($2::text[]))
    AND observation_path_hops(po.path_bytes, po.hash_size, po.hop_count) && $3::bytea[]
    AND p.payload_type <> 9 -- TRACE observation path bytes are SNR, not hop hashes.
  GROUP BY po.packet_hash
  HAVING $4::bigint = 0 OR min(po.id) < $4::bigint
  ORDER BY first_match_id DESC
  LIMIT $5::int
)
SELECT m.first_match_id, snapshot.id AS snapshot_id, m.matching_observations,
       p.packet_hash, p.payload_type, p.route_type, p.first_heard_at,
       po.heard_at AS last_heard_at, sc.name AS scope_name,
       po.observer_id, o.display_name AS observer_name, po.iata,
       po.path_length_byte, po.hash_size, po.hop_count, po.path_bytes
FROM matches m
JOIN packets p ON p.packet_hash = m.packet_hash
JOIN packet_observations po ON po.id = m.last_match_id
JOIN observers o ON o.id = po.observer_id
LEFT JOIN transport_scopes sc ON sc.id = p.scope_id
CROSS JOIN snapshot
ORDER BY m.first_match_id DESC
`

type ListNodePathPacketsParams struct {
	SnapshotID int64    `json:"snapshot_id"`
	Iatas      []string `json:"iatas"`
	Prefixes   [][]byte `json:"prefixes"`
	BeforeID   int64    `json:"before_id"`
	PageLimit  int32    `json:"page_limit"`
}

type ListNodePathPacketsRow struct {
	FirstMatchID         int64              `json:"first_match_id"`
	SnapshotID           int64              `json:"snapshot_id"`
	MatchingObservations int64              `json:"matching_observations"`
	PacketHash           []byte             `json:"packet_hash"`
	PayloadType          int16              `json:"payload_type"`
	RouteType            int16              `json:"route_type"`
	FirstHeardAt         pgtype.Timestamptz `json:"first_heard_at"`
	LastHeardAt          pgtype.Timestamptz `json:"last_heard_at"`
	ScopeName            *string            `json:"scope_name"`
	ObserverID           uuid.UUID          `json:"observer_id"`
	ObserverName         *string            `json:"observer_name"`
	Iata                 string             `json:"iata"`
	PathLengthByte       int16              `json:"path_length_byte"`
	HashSize             int16              `json:"hash_size"`
	HopCount             int16              `json:"hop_count"`
	PathBytes            []byte             `json:"path_bytes"`
}

// Prefixes are resolved globally with ResolvePathHashes before this query.
// First matching observation ID is an immutable ordering key. A snapshot excludes
// newly arriving packets/observations from all later pages, avoiding duplicates.
func (q *Queries) ListNodePathPackets(ctx context.Context, arg ListNodePathPacketsParams) ([]ListNodePathPacketsRow, error) {
	rows, err := q.db.Query(ctx, listNodePathPackets,
		arg.SnapshotID,
		arg.Iatas,
		arg.Prefixes,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodePathPacketsRow{}
	for rows.Next() {
		var i ListNodePathPacketsRow
		if err := rows.Scan(
			&i.FirstMatchID,
			&i.SnapshotID,
			&i.MatchingObservations,
			&i.PacketHash,
			&i.PayloadType,
			&i.RouteType,
			&i.FirstHeardAt,
			&i.LastHeardAt,
			&i.ScopeName,
			&i.ObserverID,
			&i.ObserverName,
			&i.Iata,
			&i.PathLengthByte,
			&i.HashSize,
			&i.HopCount,
			&i.PathBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
