#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const schemaPath = path.join(root, "openapi", "beacon-server.swagger.json");
const outDir = path.join(root, "src", "api", "generated");
const check = process.argv.includes("--check");
const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
if (schema.swagger !== "2.0") throw new Error(`Expected Swagger 2.0, got ${schema.swagger ?? "unknown"}`);

const banner = `// AUTO-GENERATED by scripts/generate-api.mjs from openapi/beacon-server.swagger.json.\n// Do not edit by hand. Regenerate with: npm run api:generate\n\n`;

const definitionNames = new Map();
for (const key of Object.keys(schema.definitions ?? {})) {
  const raw = key.split(".").at(-1) ?? key;
  const generic = raw
    .replace(/^Page-github_com_MeshCore-Beacon_beacon-server_internal_api_/, "Page")
    .replace(/[^A-Za-z0-9_$]/g, "_");
  let name = generic.replace(/_github_com_MeshCore_Beacon_beacon_server_internal_api_/g, "");
  if (!/^[A-Za-z_$]/.test(name)) name = `Model_${name}`;
  let unique = name;
  let i = 2;
  while ([...definitionNames.values()].includes(unique)) unique = `${name}_${i++}`;
  definitionNames.set(key, unique);
}

function refName(ref) {
  const key = ref.replace("#/definitions/", "");
  return definitionNames.get(key) ?? "unknown";
}

function tsType(node = {}, refPrefix = "") {
  if (node.$ref) return `${refPrefix}${refName(node.$ref)}`;
  if (node.allOf) return node.allOf.map((part) => tsType(part, refPrefix)).join(" & ");
  if (Array.isArray(node.enum) && node.enum.length) return node.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (node.type === "array") return `Array<${tsType(node.items ?? {}, refPrefix)}>`;
  if (node.type === "integer" || node.type === "number") return "number";
  if (node.type === "boolean") return "boolean";
  if (node.type === "string") return "string";
  if (node.type === "object" || node.properties || node.additionalProperties) {
    if (node.additionalProperties && !node.properties) return `Record<string, ${tsType(node.additionalProperties, refPrefix)}> ` .trim();
    if (!node.additionalProperties && Object.keys(node.properties ?? {}).length === 0) return "unknown";
    const required = new Set(node.required ?? []);
    const props = Object.entries(node.properties ?? {}).map(([name, prop]) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
      return `${key}${required.has(name) ? "" : "?"}: ${tsType(prop, refPrefix)};`;
    });
    if (node.additionalProperties) props.push(`[key: string]: ${tsType(node.additionalProperties, refPrefix)};`);
    return `{ ${props.join(" ")} }`;
  }
  return "unknown";
}

let models = banner;
for (const [key, def] of Object.entries(schema.definitions ?? {})) {
  const name = definitionNames.get(key);
  const description = def.description ? `/** ${String(def.description).replace(/\*\//g, "*\\/")} */\n` : "";
  models += `${description}export type ${name} = ${tsType(def)};\n\n`;
}

function functionName(method, route) {
  const parts = route.split("/").filter(Boolean).map((part) => {
    const clean = part.replace(/[{}]/g, "").replace(/[^A-Za-z0-9]+(.)/g, (_, c) => c.toUpperCase());
    return clean.charAt(0).toUpperCase() + clean.slice(1);
  });
  return `raw${method.toLowerCase().replace(/^./, (c) => c.toUpperCase())}${parts.join("")}`;
}

function responseSchema(op) {
  const responses = op.responses ?? {};
  const preferred = responses["200"] ?? responses["201"] ?? responses["202"] ?? responses["204"];
  return preferred?.schema;
}

const operations = [];
for (const [route, pathItem] of Object.entries(schema.paths ?? {})) {
  for (const method of ["get", "post", "put", "patch", "delete"]) {
    const op = pathItem[method];
    if (!op) continue;
    const parameters = [...(pathItem.parameters ?? []), ...(op.parameters ?? [])];
    operations.push({ route, method, op, parameters, name: functionName(method, route) });
  }
}

let client = `${banner}import { API_BASE } from "../../lib/constants";\nimport type * as Models from "./models";\n\n`;
client += `export class ApiError extends Error {\n  status: number;\n  code: string;\n  constructor(status: number, code: string, message: string) {\n    super(message); this.name = "ApiError"; this.status = status; this.code = code;\n  }\n}\n\n`;
client += `type QueryValue = string | number | boolean | undefined;\n\n`;
client += `async function request<T>(route: string, query?: Record<string, QueryValue>, init?: RequestInit): Promise<T> {\n  const url = new URL(\`\${API_BASE}\${route}\`, window.location.origin);\n  for (const [key, value] of Object.entries(query ?? {})) if (value !== undefined) url.searchParams.set(key, String(value));\n  const res = await fetch(url.toString(), init);\n  if (!res.ok) {\n    const body = await res.json().catch(() => ({ error: { code: "unknown", message: res.statusText } }));\n    throw new ApiError(res.status, body?.error?.code ?? "unknown", body?.error?.message ?? res.statusText);\n  }\n  if (res.status === 204) return undefined as T;\n  return await res.json() as T;\n}\n\n`;

for (const { route, method, parameters, name, op } of operations) {
  const pathParams = parameters.filter((p) => p.in === "path");
  const queryParams = parameters.filter((p) => p.in === "query");
  const bodyParam = parameters.find((p) => p.in === "body");
  const allParams = [...pathParams, ...queryParams];
  const required = allParams.filter((p) => p.required);
  const optional = allParams.filter((p) => !p.required);
  const fields = [...required, ...optional].map((p) => `${p.name}${p.required ? "" : "?"}: ${tsType(p.schema ?? p, "Models.")};`);
  if (bodyParam) fields.push(`${bodyParam.name || "body"}${bodyParam.required ? "" : "?"}: ${tsType(bodyParam.schema ?? {}, "Models.")};`);
  const paramsType = fields.length ? `{ ${fields.join(" ")} }` : null;
  const resultType = responseSchema(op) ? tsType(responseSchema(op), "Models.") : "unknown";
  client += fields.length
    ? `export async function ${name}(params: ${paramsType}): Promise<${resultType}> {\n`
    : `export async function ${name}(): Promise<${resultType}> {\n`;
  let routeExpr = JSON.stringify(route);
  for (const p of pathParams) routeExpr = routeExpr.replace(`{${p.name}}`, `\${encodeURIComponent(String(params.${p.name}))}`);
  if (pathParams.length) routeExpr = "`" + routeExpr.slice(1, -1).replace(/\\\$\{/g, "${") + "`";
  const queryEntries = queryParams.map((p) => `${JSON.stringify(p.name)}: params${fields.length ? "" : "?"}.${p.name}`).join(", ");
  const methodUpper = method.toUpperCase();
  const initParts = [];
  if (methodUpper !== "GET") initParts.push(`method: ${JSON.stringify(methodUpper)}`);
  if (bodyParam) {
    initParts.push(`headers: { "Content-Type": "application/json" }`);
    initParts.push(`body: JSON.stringify(params.${bodyParam.name || "body"})`);
  }
  client += `  return request<${resultType}>(${routeExpr}, ${queryParams.length ? `{ ${queryEntries} }` : "undefined"}${initParts.length ? `, { ${initParts.join(", ")} }` : ""});\n`;
  client += `}\n\n`;
}

function writeOrCheck(file, content) {
  const target = path.join(outDir, file);
  if (check) {
    const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
    if (existing !== content) {
      console.error(`${path.relative(root, target)} is out of date. Run npm run api:generate.`);
      process.exitCode = 1;
    }
  } else {
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(target, content);
  }
}

writeOrCheck("models.ts", `${models.trimEnd()}\n`);
writeOrCheck("client.ts", `${client.trimEnd()}\n`);
