import type * as Models from '../api/generated/models';

// Application pagination normalizes absent wire cursors to null.
export type CursorPage<T> = Omit<
  Models.PagePacketSummary,
  'items' | 'nextCursor' | 'nextPageToken'
> & {
  items: T[];
  nextCursor: number | null;
  nextPageToken?: string | null;
};
export type LatestObserver = Models.PacketLatestObserver;
export type PacketSummary = Models.PacketSummary;
export type ResolvedNode = Models.ResolvedNode;
// Route presentation may attach its separately transmitted path-hash prefix.
export type ResolvedHop = Models.ResolvedHop & { hashBytes?: Models.RouteHop['hashBytes'] };
export type PathLength = Models.PacketPathLength;
export type Observation = Omit<Models.PacketObservationDetail, 'propagationTimeMs'> & {
  propagationTimeMs?: Exclude<Models.PacketObservationDetail['propagationTimeMs'], null>;
};
export type PacketHeader = Models.PacketHeader;
export type TransportCodes = Models.PacketTransportCodes;
// Payload-specific JSON is narrowed by the adapter; it is not a generated byte array.
export type PacketDetail = Omit<
  Models.Packet,
  'parsedPayload' | 'observations' | 'resolvedRoute'
> & {
  parsedPayload?: Record<string, unknown> | string;
  observations: Observation[];
  resolvedRoute?: ResolvedHop[];
};
export type IataCode = Models.IATA;
export type RegionSummary = Models.RegionSummary;
export type Region = Models.Region;
export type BrokerStatus = Models.BrokerStatus;
export type RouteHop = Models.RouteHop;
export type KnownRoute = Models.KnownRoute;
export type CrossIATAHop = Models.CrossIATAHop;
export type CrossIATARoute = Models.CrossIATARoute;
export type TraceType = Models.TraceTagSummary['traceType'];
export type TraceTagSummary = Models.TraceTagSummary;
export type ResolvedHopLite = Models.ResolvedHopLite;
export type RawHop = Models.RawHop;
export type TracePacket = Models.TracePacket;
export type TraceDetail = Models.TraceDetail;
