import type { Map as MapLibreMap } from "maplibre-gl";
import {
  FOCUSED_NEIGHBORS_LAYER_ID,
  FOCUSED_NEIGHBORS_BASE_LAYER_ID,
  FOCUSED_SELECTED_BACKDROP_LAYER_ID,
  IATA_BORDERS_LINE_LAYER_ID,
  NEIGHBORS_LINE_LAYER_ID,
  NODES_CLUSTER_BREAKDOWN_LAYER_ID,
  NODES_CLUSTER_FALLBACK_LAYER_ID,
  NODES_CLUSTER_HALO_LAYER_ID,
  NODES_CLUSTER_LAYER_ID,
  NODES_DOT_LAYER_ID,
  NODES_GLOW_LAYER_ID,
  NODES_POINT_LAYER_ID,
  NODES_SELECTED_LAYER_ID,
  NODES_SELECTED_LEAF_LAYER_ID,
  PACKET_FLOW_DOT_HALO_LAYER_ID,
  PACKET_FLOW_DOT_LAYER_ID,
  PACKET_FLOW_PULSE_GLOW_LAYER_ID,
  PACKET_FLOW_PULSE_RING_LAYER_ID,
  PACKET_FLOW_TRAIL_LAYER_ID,
} from "./types";

// Bottom-to-top order for Beacon-owned map layers. Hooks can run again independently after a style
// switch, so creation-time `beforeId` alone is not enough: moving every layer that currently exists
// makes the final order deterministic regardless of which hook restored its layer last.
export const MAP_OVERLAY_LAYER_ORDER = [
  IATA_BORDERS_LINE_LAYER_ID,
  NEIGHBORS_LINE_LAYER_ID,
  NODES_GLOW_LAYER_ID,
  NODES_SELECTED_LAYER_ID,
  NODES_SELECTED_LEAF_LAYER_ID,
  NODES_CLUSTER_HALO_LAYER_ID,
  NODES_CLUSTER_FALLBACK_LAYER_ID,
  NODES_CLUSTER_LAYER_ID,
  NODES_CLUSTER_BREAKDOWN_LAYER_ID,
  NODES_DOT_LAYER_ID,
  FOCUSED_SELECTED_BACKDROP_LAYER_ID,
  FOCUSED_NEIGHBORS_BASE_LAYER_ID,
  NODES_POINT_LAYER_ID,
  FOCUSED_NEIGHBORS_LAYER_ID,
  PACKET_FLOW_TRAIL_LAYER_ID,
  PACKET_FLOW_DOT_HALO_LAYER_ID,
  PACKET_FLOW_DOT_LAYER_ID,
  PACKET_FLOW_PULSE_GLOW_LAYER_ID,
  PACKET_FLOW_PULSE_RING_LAYER_ID,
] as const;

export function syncMapOverlayLayerOrder(map: Pick<MapLibreMap, "getLayer" | "moveLayer">): void {
  for (const layerId of MAP_OVERLAY_LAYER_ORDER) {
    if (map.getLayer(layerId)) map.moveLayer(layerId);
  }
}
